#!/usr/bin/env python3
"""Visualize finite-window 3-color profile coverage and contribution."""

from __future__ import annotations

import os
from dataclasses import dataclass
from pathlib import Path

os.environ.setdefault(
    "MPLCONFIGDIR", str(Path(os.environ.get("TMPDIR", "/tmp")) / "llc_uace_mplconfig")
)

import matplotlib.pyplot as plt
import numpy as np

from uace_bound_explorer import format_probability
from uace_multicolor_chunk_aggregate import (
    DEFAULT_REPORTS,
    ChunkRow,
    falling_factorial,
    include_nonoverlapping,
    interval_coverage,
    parse_report,
)
from uace_multicolor_summary import parse_report as parse_summary_report


@dataclass(frozen=True)
class WindowPoint:
    label: str
    key_label: str
    coverage: float
    contribution: float
    cumulative: float
    min_rank: int


def two_color_baseline(k: int, pe: float) -> float:
    rows = parse_summary_report(Path("research/uace_pair_preemption_exact.md"), known_sections=14)
    for row in rows:
        if row.colors == 2 and row.k == k and abs(row.pe - pe) < 1e-12:
            return row.extra
    raise ValueError("could not find two-color baseline")


def included_rows() -> list[ChunkRow]:
    rows = [row for report in DEFAULT_REPORTS if Path(report).exists() for row in parse_report(Path(report))]
    return [item.row for item in include_nonoverlapping(rows) if item.status == "included"]


def window_points(*, k: int, pe: float, length: int = 16) -> list[WindowPoint]:
    rows = included_rows()
    coverage = interval_coverage(
        [type("Included", (), {"status": "included", "row": row})() for row in rows],
        known_sections=14,
    )
    choices = falling_factorial(k - 1, 2)
    mask_prob = (pe**2) * ((1.0 - pe) ** (length - 2))
    running = 0.0
    out: list[WindowPoint] = []
    for row in sorted(rows, key=lambda item: (item.key, item.start, item.source.name)):
        contribution = mask_prob * choices * row.multiplicity * row.weighted_q[pe]
        running += contribution
        key_label = f"{row.attempt.replace('phase-III ', '')} {row.mask_sections}"
        label = f"{key_label}\n{row.start}-{row.end}"
        out.append(
            WindowPoint(
                label=label,
                key_label=key_label,
                coverage=coverage[row.key],
                contribution=contribution,
                cumulative=running,
                min_rank=row.min_preempt_rank,
            )
        )
    return out


def write_report(points: list[WindowPoint], baseline: float, output: Path) -> None:
    lines = [
        "# Multi-Color Coverage Figure Summary",
        "",
        "This report is generated by `research/generate_multicolor_coverage_figure.py`.",
        "",
        f"- two-color exact baseline at `K=40, p_e=0.1`: `{format_probability(baseline)}`",
        f"- final 3-color finite-window cumulative extra: `{format_probability(points[-1].cumulative)}`",
        f"- final ratio to two-color exact: `{format_probability(points[-1].cumulative / baseline)}`",
        f"- max represented-mask coverage: `{format_probability(max(point.coverage for point in points))}`",
        "",
        "| window | coverage for represented mask | contribution | cumulative extra | cumulative/two-color | min rank |",
        "|---|---:|---:|---:|---:|---:|",
    ]
    for point in points:
        lines.append(
            "| "
            + " | ".join(
                [
                    point.label.replace("\n", " "),
                    format_probability(point.coverage),
                    format_probability(point.contribution),
                    format_probability(point.cumulative),
                    format_probability(point.cumulative / baseline),
                    str(point.min_rank),
                ]
            )
            + " |"
        )
    output.write_text("\n".join(lines) + "\n", encoding="utf-8")


def plot(points: list[WindowPoint], baseline: float, output: Path) -> None:
    x = np.arange(len(points))
    contribution = np.array([point.contribution for point in points])
    cumulative = np.array([point.cumulative for point in points])
    coverage_by_key: dict[str, float] = {}
    for point in points:
        coverage_by_key[point.key_label] = max(coverage_by_key.get(point.key_label, 0.0), point.coverage)

    fig, axes = plt.subplots(2, 2, figsize=(13.2, 8.0), constrained_layout=True)

    ax = axes[0, 0]
    ax.semilogy(x, cumulative, "o-", color="#2f5597", label="3-color cumulative")
    ax.axhline(baseline, color="#c55a11", linestyle="--", label="2-color exact")
    ax.set_title("Cumulative finite-window 3-color contribution")
    ax.set_xlabel("included window index")
    ax.set_ylabel("K=40, pe=0.1 extra")
    ax.grid(axis="y", alpha=0.25, which="both")
    ax.legend(fontsize=8)

    ax = axes[0, 1]
    ax.semilogy(x, contribution, "s", color="#7030a0")
    ax.set_title("Per-window contribution")
    ax.set_xlabel("included window index")
    ax.set_ylabel("extra contribution")
    ax.grid(axis="y", alpha=0.25, which="both")

    ax = axes[1, 0]
    keys = list(coverage_by_key)
    y = np.arange(len(keys))
    vals = np.array([coverage_by_key[key] for key in keys])
    ax.barh(y, vals, color="#70ad47")
    ax.set_yticks(y)
    ax.set_yticklabels(keys, fontsize=7)
    ax.set_xlabel("coverage of represented profile family")
    ax.set_xlim(0.0, max(0.03, vals.max() * 1.2))
    ax.set_title("Coverage remains finite-window")
    ax.grid(axis="x", alpha=0.25)

    ax = axes[1, 1]
    ax.plot(x, cumulative / baseline, "o-", color="#1f7a8c")
    ax.set_title("Cumulative 3-color / 2-color exact")
    ax.set_xlabel("included window index")
    ax.set_ylabel("ratio")
    ax.set_ylim(0.0, max(0.004, (cumulative / baseline).max() * 1.25))
    ax.grid(axis="y", alpha=0.25)

    fig.suptitle("Phase III 3-color profile chunks remain below pair-preemption scale", fontsize=14)
    output.parent.mkdir(parents=True, exist_ok=True)
    fig.savefig(output, dpi=190)


def main() -> int:
    points = window_points(k=40, pe=0.1)
    baseline = two_color_baseline(k=40, pe=0.1)
    plot(points, baseline, Path("research/figures/uace_multicolor_coverage.png"))
    write_report(points, baseline, Path("research/uace_multicolor_coverage_figure.md"))
    print("wrote research/figures/uace_multicolor_coverage.png")
    print("wrote research/uace_multicolor_coverage_figure.md")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
