#!/usr/bin/env python3
"""Plot Phase I/II schedule floors against finite-K false/PHP corrections."""

from __future__ import annotations

import os
from dataclasses import dataclass
from pathlib import Path

os.environ.setdefault(
    "MPLCONFIGDIR", str(Path(os.environ.get("TMPDIR", "/tmp")) / "llc_uace_mplconfig")
)

import matplotlib.pyplot as plt
import numpy as np

from uace_bound_explorer import bad_mask_probability, expected_a_list_size, format_probability
from uace_interference_bound import interference_moments
from uace_schedule_bound import schedule_bad_masks


@dataclass(frozen=True)
class Row:
    phase: int
    k: int
    pe: float
    schedule: float
    lambda_a: float
    e_false: float
    php_bound: float
    pdp_pred: float


def compute_rows(
    *,
    phases: tuple[int, ...] = (1, 2),
    ks: tuple[int, ...] = (30, 40, 100),
    pes: tuple[float, ...] = (0.1, 0.2, 0.3),
    length: int = 16,
    memory: int = 3,
    j: int = 16,
    parity_bits_per_section: int = 8,
    seed: int = 0,
) -> list[Row]:
    rows: list[Row] = []
    bad_masks = {phase: schedule_bad_masks(length, memory, phase, seed) for phase in phases}
    for phase in phases:
        for k in ks:
            for pe in pes:
                schedule = bad_mask_probability(bad_masks[phase], length, pe)
                lambda_a = expected_a_list_size(k, j, pe)
                moments = interference_moments(
                    k=k,
                    length=length,
                    j=j,
                    memory=memory,
                    phase=phase,
                    pe=pe,
                    parity_bits_per_section=parity_bits_per_section,
                    seed=seed,
                )
                e_false = sum(item.expected_false_survivors for item in moments)
                php = min(1.0, e_false / k)
                rows.append(
                    Row(
                        phase=phase,
                        k=k,
                        pe=pe,
                        schedule=schedule,
                        lambda_a=lambda_a,
                        e_false=e_false,
                        php_bound=php,
                        pdp_pred=min(1.0, schedule + php),
                    )
                )
    return rows


def write_report(rows: list[Row], output: Path) -> None:
    lines = [
        "# Phase I/II Interference Scale Summary",
        "",
        "This report is generated by `research/generate_phase12_interference_scales.py`.",
        "",
        "| phase | K | pe | schedule UE | lambda_A | E false | PHP bound | PHP/schedule |",
        "|---:|---:|---:|---:|---:|---:|---:|---:|",
    ]
    for row in rows:
        ratio = row.php_bound / row.schedule if row.schedule else float("inf")
        lines.append(
            "| "
            + " | ".join(
                [
                    str(row.phase),
                    str(row.k),
                    f"{row.pe:.3f}",
                    format_probability(row.schedule),
                    f"{row.lambda_a:.3f}",
                    format_probability(row.e_false),
                    format_probability(row.php_bound),
                    format_probability(ratio),
                ]
            )
            + " |"
        )
    lines.extend(
        [
            "",
            "Readout: in this finite instance, Phase I and Phase II visible PDP is controlled by the schedule floor.  The rank-corrected finite-K false/PHP correction is many orders of magnitude smaller for K=30 and K=40, and remains small even at K=100 for Phase I/II.",
            "",
        ]
    )
    output.write_text("\n".join(lines), encoding="utf-8")


def plot(rows: list[Row], output: Path) -> None:
    colors = {0.1: "#2f5597", 0.2: "#c55a11", 0.3: "#70ad47"}
    markers = {0.1: "o", 0.2: "s", 0.3: "^"}
    phases = (1, 2)
    ks = sorted({row.k for row in rows})
    pes = sorted({row.pe for row in rows})

    fig, axes = plt.subplots(2, 2, figsize=(12.5, 8.0), constrained_layout=True)
    floor = 1e-20

    for col, phase in enumerate(phases):
        phase_rows = [row for row in rows if row.phase == phase]
        ax = axes[0, col]
        for pe in pes:
            selected = sorted([row for row in phase_rows if abs(row.pe - pe) < 1e-12], key=lambda r: r.k)
            x = np.array([row.k for row in selected])
            schedule = np.array([row.schedule for row in selected])
            php = np.array([max(row.php_bound, floor) for row in selected])
            ax.semilogy(
                x,
                schedule,
                marker=markers[pe],
                color=colors[pe],
                linestyle="-",
                label=f"pe={pe:.1f} schedule",
            )
            ax.semilogy(
                x,
                php,
                marker=markers[pe],
                color=colors[pe],
                linestyle="--",
                label=f"pe={pe:.1f} PHP bound",
            )
        ax.set_title(f"Phase {phase}: schedule floor vs finite-K correction")
        ax.set_xlabel("K")
        ax.set_ylabel("probability")
        ax.set_xticks(ks)
        ax.set_ylim(1e-20, 1.2)
        ax.grid(axis="y", alpha=0.25, which="both")
        ax.legend(fontsize=7, ncol=2)

        ax_ratio = axes[1, col]
        for pe in pes:
            selected = sorted([row for row in phase_rows if abs(row.pe - pe) < 1e-12], key=lambda r: r.k)
            x = np.array([row.k for row in selected])
            ratio = np.array([max(row.php_bound / row.schedule, floor) for row in selected])
            ax_ratio.semilogy(
                x,
                ratio,
                marker=markers[pe],
                color=colors[pe],
                linestyle="-",
                label=f"pe={pe:.1f}",
            )
        ax_ratio.set_title(f"Phase {phase}: correction / schedule ratio")
        ax_ratio.set_xlabel("K")
        ax_ratio.set_ylabel("PHP bound / schedule")
        ax_ratio.set_xticks(ks)
        ax_ratio.set_ylim(1e-20, 1e-3)
        ax_ratio.grid(axis="y", alpha=0.25, which="both")
        ax_ratio.legend(fontsize=8)

    fig.suptitle("Phase I/II finite-K interference corrections are below visible PDP scale", fontsize=14)
    output.parent.mkdir(parents=True, exist_ok=True)
    fig.savefig(output, dpi=190)


def main() -> int:
    rows = compute_rows()
    plot(rows, Path("research/figures/uace_phase12_interference_scales.png"))
    write_report(rows, Path("research/uace_phase12_interference_scales.md"))
    print("wrote research/figures/uace_phase12_interference_scales.png")
    print("wrote research/uace_phase12_interference_scales.md")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
