#!/usr/bin/env python3
"""K-dependent analytical components for LLC/UACE validation."""

from __future__ import annotations

import argparse
from pathlib import Path

from uace_bound_explorer import (
    bad_mask_probability,
    circular_run_probability,
    format_probability,
    rank_peeling_bad_masks,
    tagged_collision_probability,
)
from uace_schedule_bound import schedule_bad_masks


DEFAULT_KS = (30, 40, 100)
DEFAULT_PES = (0.05, 0.1, 0.15, 0.2, 0.3)


def tagged_unconditional_collision_probability(k: int, j: int, pe: float) -> float:
    """Probability a tagged section is both unerased and collided."""
    return (1.0 - pe) * tagged_collision_probability(k, j, pe)


def any_tagged_collision_probability(k: int, length: int, j: int, pe: float) -> float:
    pi = tagged_unconditional_collision_probability(k, j, pe)
    return 1.0 - (1.0 - pi) ** length


def build_report(args: argparse.Namespace) -> str:
    phase2_bad = schedule_bad_masks(args.L, args.M, 2, args.seed)
    phase3_bad = schedule_bad_masks(args.L, args.M, 3, args.seed)
    rank_bad = rank_peeling_bad_masks(args.L, args.M, args.seed)

    lines = [
        "# UACE K-Sweep Analytical Components",
        "",
        "This report is generated by `research/uace_k_sweep_components.py`.",
        "",
        f"- `L = {args.L}`",
        f"- `M = {args.M}`",
        f"- `J = {args.J}`",
        f"- matrix seed: `{args.seed}`",
        "",
        "| K | pe | phase-II schedule | phase-III schedule | ideal rank | rho tagged | any tagged collision | collision run M |",
        "|---:|---:|---:|---:|---:|---:|---:|---:|",
    ]

    for k in args.Ks:
        for pe in args.pes:
            rho = tagged_collision_probability(k, args.J, pe)
            pi_any = any_tagged_collision_probability(k, args.L, args.J, pe)
            run = circular_run_probability(args.L, args.M, rho)
            lines.append(
                "| "
                + " | ".join(
                    [
                        str(k),
                        f"{pe:.3f}",
                        format_probability(bad_mask_probability(phase2_bad, args.L, pe)),
                        format_probability(bad_mask_probability(phase3_bad, args.L, pe)),
                        format_probability(bad_mask_probability(rank_bad, args.L, pe)),
                        format_probability(rho),
                        format_probability(pi_any),
                        format_probability(run),
                    ]
                )
                + " |"
            )

    lines.extend(
        [
            "",
            "Interpretation:",
            "",
            "- `phase-II/III schedule` are K-independent erasure-only decoder-flow terms.",
            "- `rho tagged` is conditioned on the tagged section not being erased.",
            "- `any tagged collision` is an upper-scale proxy for seeing at least one collided tagged section in a user codeword.",
            "- `collision run M` is the exact circular probability of M consecutive collided tagged sections using `rho tagged`; it is a conservative path-term scale, not the full false-path theorem.",
            "",
        ]
    )
    return "\n".join(lines)


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--L", type=int, default=16)
    parser.add_argument("--M", type=int, default=3)
    parser.add_argument("--J", type=int, default=16)
    parser.add_argument("--seed", type=int, default=0)
    parser.add_argument("--Ks", type=int, nargs="+", default=list(DEFAULT_KS))
    parser.add_argument("--pes", type=float, nargs="+", default=list(DEFAULT_PES))
    parser.add_argument("--output", type=Path, default=None)
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    content = build_report(args)
    if args.output is None:
        print(content)
    else:
        args.output.write_text(content + "\n", encoding="utf-8")
        print(f"wrote {args.output}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
