#!/usr/bin/env python3
"""Consolidate phase-III targeted path-interference probes."""

from __future__ import annotations

import argparse
import re
from collections import defaultdict
from dataclasses import dataclass
from pathlib import Path

import numpy as np

from uace_bound_explorer import bad_mask_probability, format_probability
from uace_interference_bound import interference_moments
from uace_schedule_bound import schedule_bad_masks


DEFAULT_FILES = (
    "research/uace_targeted_probe_K30_phase3_pe010_trials2.md",
    "research/uace_targeted_probe_K30_phase3_pe020_trials2.md",
    "research/uace_targeted_probe_K30_phase3_pe030_trials5.md",
    "research/uace_targeted_probe_K40_phase3_pe010_trial1_cap5m.md",
    "research/uace_targeted_probe_K40_phase3_pe030_trials5.md",
    "research/uace_targeted_probe_K40_phase3_pe030_seed5401_cap5m.md",
    "research/uace_targeted_probe_K40_phase3_pe030_seed5403_cap5m.md",
)


@dataclass(frozen=True)
class Row:
    source: str
    k: int
    pe: float
    seed: int
    schedule_fail: float
    success_users: int
    checked: int
    path_fail: int
    wrong_path: int
    aborted: int
    targeted_php: float
    node_visits: int
    seconds: float


def scalar(pattern: str, text: str, name: str, cast):
    match = re.search(pattern, text)
    if not match:
        raise ValueError(f"missing {name}")
    return cast(match.group(1))


def parse_file(path: Path) -> list[Row]:
    text = path.read_text(encoding="utf-8")
    k = scalar(r"`K = (\d+)`", text, "K", int)
    pe = scalar(r"`pe = ([0-9.]+)`", text, "pe", float)
    rows = []
    for line in text.splitlines():
        if not re.match(r"\| \d+ \| [0-9.]+ \|", line):
            continue
        parts = [item.strip() for item in line.strip("|").split("|")]
        rows.append(
            Row(
                source=path.name,
                k=k,
                pe=pe,
                seed=int(parts[0]),
                schedule_fail=float(parts[1]),
                success_users=int(parts[2]),
                checked=int(parts[3]),
                path_fail=int(parts[4]),
                wrong_path=int(parts[5]),
                aborted=int(parts[6]),
                targeted_php=float(parts[7]),
                node_visits=int(parts[8]),
                seconds=float(parts[9]),
            )
        )
    return rows


def build_report(args: argparse.Namespace) -> str:
    by_seed: dict[tuple[int, float, int], Row] = {}
    for item in args.files:
        for row in parse_file(Path(item)):
            key = (row.k, row.pe, row.seed)
            # Later files intentionally override earlier capped rows.
            by_seed[key] = row

    groups: dict[tuple[int, float], list[Row]] = defaultdict(list)
    for row in by_seed.values():
        groups[(row.k, row.pe)].append(row)

    lines = [
        "# Phase-III Targeted Path-Interference Summary",
        "",
        "This report is generated by `research/uace_phase3_targeted_summary.py`.",
        "",
        "The targeted probe checks users whose erasure masks are recoverable by the current phase-III schedule.  It measures whether those users are lost anyway because the first parity-consistent path is wrong or because no valid path is found within the node cap.",
        "",
        "| K | pe | trials | schedule UE | sampled schedule fail | schedule-success checked | path fail | wrong path | aborted | first-moment PHP bound | targeted PHP | mean seconds |",
        "|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|",
    ]
    for (k, pe), rows in sorted(groups.items()):
        schedule_bad = schedule_bad_masks(args.L, args.M, 3, args.seed)
        schedule_ue = bad_mask_probability(schedule_bad, args.L, pe)
        moments = interference_moments(
            k=k,
            length=args.L,
            j=args.J,
            memory=args.M,
            phase=3,
            pe=pe,
            parity_bits_per_section=args.R,
        )
        php_bound = sum(item.expected_false_survivors for item in moments) / k
        lines.append(
            "| "
            + " | ".join(
                [
                    str(k),
                    f"{pe:.3f}",
                    str(len(rows)),
                    format_probability(schedule_ue),
                    format_probability(float(np.mean([row.schedule_fail for row in rows]))),
                    str(sum(row.checked for row in rows)),
                    str(sum(row.path_fail for row in rows)),
                    str(sum(row.wrong_path for row in rows)),
                    str(sum(row.aborted for row in rows)),
                    format_probability(php_bound),
                    format_probability(float(np.mean([row.targeted_php for row in rows]))),
                    f"{float(np.mean([row.seconds for row in rows])):.2f}",
                ]
            )
            + " |"
        )

    lines.extend(
        [
            "",
            "Readout:",
            "",
            "- All completed targeted phase-III checks have `wrong path = 0` and `targeted PHP = 0`.",
            "- After re-running hard K=40 seeds with larger node caps, `aborted = 0` for the summarized rows.",
            "- This validates the phase-III path-interference term on schedule-success users for the listed K/pe points, but it is still a semi-genie check rather than a full root sweep over every schedule-failed root.",
            "",
        ]
    )
    return "\n".join(lines)


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--L", type=int, default=16)
    parser.add_argument("--M", type=int, default=3)
    parser.add_argument("--J", type=int, default=16)
    parser.add_argument("--R", type=int, default=8)
    parser.add_argument("--seed", type=int, default=0)
    parser.add_argument("--files", nargs="+", default=list(DEFAULT_FILES))
    parser.add_argument("--output", type=Path, default=Path("research/uace_phase3_targeted_summary.md"))
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    content = build_report(args)
    if args.output:
        args.output.write_text(content + "\n", encoding="utf-8")
        print(f"wrote {args.output}")
    else:
        print(content)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
