#!/usr/bin/env python3
"""Break down LLC/UACE false-survivor first moment by attempt and weight."""

from __future__ import annotations

import argparse
from pathlib import Path

from uace_bound_explorer import bad_mask_probability, format_probability
from uace_interference_bound import interference_moments
from uace_schedule_bound import schedule_bad_masks


DEFAULT_KS = (30, 40, 100)
DEFAULT_PES = (0.1, 0.2, 0.3)


def build_report(args: argparse.Namespace) -> str:
    lines = [
        "# UACE False-Survivor Contribution Breakdown",
        "",
        "This report is generated by `research/uace_false_contribution_breakdown.py`.",
        "",
        "Each row is one contribution",
        "",
        "$$",
        "\\sum_e A_a(w,e)\\lambda_A^{L-w}2^{-e}",
        "$$",
        "",
        "from the accepted-shape first-moment bound, where `e = rank([A B]) - rank(A)` is the exact GF(2) exponent of the erased-info feasibility system.  The `PHP contrib` column divides this contribution by `K`.",
        "",
    ]

    for phase in args.phases:
        bad_masks = schedule_bad_masks(args.L, args.M, phase, args.seed)
        lines.extend(
            [
                f"## Phase {phase}",
                "",
                "| K | pe | schedule UE | attempt | weight w | accepted shapes | rank exponent | E false contrib | PHP contrib | share |",
                "|---:|---:|---:|---|---:|---:|---:|---:|---:|---:|",
            ]
        )
        for k in args.Ks:
            for pe in args.pes:
                schedule_ue = bad_mask_probability(bad_masks, args.L, pe)
                moments = interference_moments(
                    k=k,
                    length=args.L,
                    j=args.J,
                    memory=args.M,
                    phase=phase,
                    pe=pe,
                    parity_bits_per_section=args.R,
                    seed=args.seed,
                )
                total = sum(moment.expected_false_survivors for moment in moments)
                rows = []
                for moment in moments:
                    for weight, count, exponent, contribution in moment.weight_contributions:
                        rows.append((contribution, moment.name, weight, count, exponent))
                for contribution, name, weight, count, exponent in sorted(rows, reverse=True)[: args.top]:
                    share = contribution / total if total > 0 else 0.0
                    lines.append(
                        "| "
                        + " | ".join(
                            [
                                str(k),
                                f"{pe:.3f}",
                                format_probability(schedule_ue),
                                name,
                                str(weight),
                                str(count),
                                str(exponent),
                                format_probability(contribution),
                                format_probability(contribution / k),
                                f"{share:.3f}",
                            ]
                        )
                        + " |"
                    )
        lines.append("")

    lines.extend(
        [
            "Readout:",
            "",
            "- Large `share` rows identify the exact attempt/erasure-weight class that a dependency-aware path DP should target first.",
            "- In the current benchmark, phase-III false-survivor mass is dominated by the root-0/root-6 two-erasure accepted shapes.",
            "- Its absolute value remains tiny for K=30/K=40, but the K=100 rows show why a dependency-aware refinement is needed before making a publish-level claim for larger loads.",
            "",
        ]
    )
    return "\n".join(lines)


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--L", type=int, default=16)
    parser.add_argument("--M", type=int, default=3)
    parser.add_argument("--J", type=int, default=16)
    parser.add_argument("--R", type=int, default=8)
    parser.add_argument("--seed", type=int, default=0)
    parser.add_argument("--Ks", type=int, nargs="+", default=list(DEFAULT_KS))
    parser.add_argument("--pes", type=float, nargs="+", default=list(DEFAULT_PES))
    parser.add_argument("--phases", type=int, nargs="+", default=[2, 3], choices=(1, 2, 3))
    parser.add_argument("--top", type=int, default=4)
    parser.add_argument("--output", type=Path, default=Path("research/uace_false_contribution_breakdown.md"))
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    content = build_report(args)
    if args.output:
        args.output.write_text(content + "\n", encoding="utf-8")
        print(f"wrote {args.output}")
    else:
        print(content)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
