#!/usr/bin/env python3
"""Merge pre-true verifier reports with selective reruns.

The base report may contain aborted users.  One or more override reports can
rerun those users at a higher cap.  This script replaces matching user rows
and rebuilds the aggregate table, yielding a reproducible certificate without
rerunning already completed users.
"""

from __future__ import annotations

import argparse
import re
from dataclasses import dataclass
from pathlib import Path


@dataclass(frozen=True)
class ReportMeta:
    k: int
    l: int
    m: int
    pe: float
    phase: int
    seed: int
    schedule_fail: float
    schedule_success_users: int
    seconds: float


@dataclass(frozen=True)
class UserRow:
    seed: int
    user: int
    attempt: str
    status: str
    visits: int


def scalar_int(pattern: str, text: str, name: str) -> int:
    match = re.search(pattern, text)
    if not match:
        raise ValueError(f"missing {name}")
    return int(match.group(1))


def scalar_float(pattern: str, text: str, name: str) -> float:
    match = re.search(pattern, text)
    if not match:
        raise ValueError(f"missing {name}")
    return float(match.group(1))


def parse_report(path: Path) -> tuple[ReportMeta, list[UserRow]]:
    text = path.read_text(encoding="utf-8")
    main_rows = []
    user_rows: list[UserRow] = []
    for line in text.splitlines():
        if not line.startswith("| "):
            continue
        parts = [item.strip() for item in line.strip("|").split("|")]
        if len(parts) == 5 and parts[0].isdigit() and parts[1].isdigit():
            user_rows.append(
                UserRow(
                    seed=int(parts[0]),
                    user=int(parts[1]),
                    attempt=parts[2],
                    status=parts[3],
                    visits=int(parts[4]),
                )
            )
        elif len(parts) == 13 and parts[0].isdigit():
            main_rows.append(parts)
    if len(main_rows) != 1:
        raise ValueError(f"expected one main row in {path}, found {len(main_rows)}")
    main = main_rows[0]
    meta = ReportMeta(
        k=scalar_int(r"`K = (\d+)`", text, "K"),
        l=scalar_int(r"`L = (\d+)`", text, "L"),
        m=scalar_int(r"`M = (\d+)`", text, "M"),
        pe=scalar_float(r"`pe = ([0-9.]+)`", text, "pe"),
        phase=scalar_int(r"`phase = (\d+)`", text, "phase"),
        seed=int(main[0]),
        schedule_fail=float(main[1]),
        schedule_success_users=int(main[2]),
        seconds=float(main[12]),
    )
    if not user_rows:
        raise ValueError(f"no user rows in {path}")
    return meta, user_rows


def build_report(base: Path, overrides: list[Path]) -> str:
    meta, rows = parse_report(base)
    by_user = {row.user: row for row in rows}
    seconds = meta.seconds
    sources = [base]
    for override in overrides:
        override_meta, override_rows = parse_report(override)
        if (override_meta.k, override_meta.pe, override_meta.seed) != (meta.k, meta.pe, meta.seed):
            raise ValueError(f"override {override} does not match base K/pe/seed")
        sources.append(override)
        seconds += override_meta.seconds
        for row in override_rows:
            by_user[row.user] = row

    merged = [by_user[user] for user in sorted(by_user)]
    phase_i = sum(row.status == "phase_i" for row in merged)
    checked = len(merged) - phase_i
    wrong = sum(row.status == "wrong_preemption" for row in merged)
    early = sum(row.status == "early_correct" for row in merged)
    missing = sum(row.status == "true_missing" for row in merged)
    invalid = sum(row.status == "true_invalid" for row in merged)
    aborted = sum(row.status == "aborted" for row in merged)
    completed = checked - aborted
    visits = sum(row.visits for row in merged)

    lines = [
        "# UACE Pre-True-Path Preemption Probe",
        "",
        "This merged report is generated by `research/uace_pretrue_merge_certificate.py`.",
        "",
        f"- `K = {meta.k}`",
        f"- `L = {meta.l}`",
        f"- `M = {meta.m}`",
        f"- `pe = {meta.pe}`",
        f"- `phase = {meta.phase}`",
        "- trials: `1`",
        "- max nodes per checked user: `merged`",
        "- only users: `all with selective high-cap reruns`",
        "- schedule UE: `n/a`",
        "- sources: `" + ", ".join(str(path) for path in sources) + "`",
        "",
        "Summary:",
        "",
        f"- checked path users: `{checked}`",
        f"- completed path users: `{completed}`",
        f"- wrong preemptions: `{wrong}`",
        "",
        "| seed | schedule fail | schedule-success users | phase-I users | checked | completed | wrong preemptions | early correct | true missing | true invalid | aborted | node visits | seconds |",
        "|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|",
        f"| {meta.seed} | {meta.schedule_fail:.6f} | {meta.schedule_success_users} | {phase_i} | {checked} | {completed} | {wrong} | {early} | {missing} | {invalid} | {aborted} | {visits} | {seconds:.2f} |",
        "",
        "Interpretation:",
        "",
        "- This is a merged certificate: base completed rows are reused and aborted users are replaced by selective high-cap reruns.",
        "- A `wrong preemption` is a final-valid decoded message before the tagged user's true path and different from the tagged message.",
        "",
        "User rows:",
        "",
        "| seed | user | attempt | status | node visits |",
        "|---:|---:|---|---|---:|",
    ]
    for row in merged:
        lines.append(f"| {row.seed} | {row.user} | {row.attempt} | {row.status} | {row.visits} |")
    lines.append("")
    return "\n".join(lines)


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--base", type=Path, required=True)
    parser.add_argument("--override", type=Path, nargs="+", required=True)
    parser.add_argument("--output", type=Path, required=True)
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    content = build_report(args.base, args.override)
    args.output.write_text(content + "\n", encoding="utf-8")
    print(f"wrote {args.output}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
