#!/usr/bin/env python3
"""Overlay analytical UACE bounds with feasible empirical LLC probes."""

from __future__ import annotations

import argparse
import time
from pathlib import Path
from types import SimpleNamespace

import numpy as np

from uace_bound_explorer import (
    BoundRow,
    bad_mask_probability,
    compute_row,
    format_probability,
    rank_peeling_bad_masks,
)
from uace_empirical_probe import TrialMetrics, run_trial
from uace_schedule_bound import schedule_bad_masks


DEFAULT_PES = (0.0, 0.05, 0.1, 0.15, 0.2)


def empirical_summary(metrics: list[TrialMetrics]) -> dict[str, float]:
    fields = (
        "pdp",
        "php",
        "decoded",
        "correct",
        "false_positive",
        "pge2_erasure_emp",
        "schedule_fail_emp",
        "rank_fail_emp",
    )
    return {
        field: float(np.mean([getattr(item, field) for item in metrics]))
        for field in fields
    }


def run_empirical_for_pe(args: argparse.Namespace, pe: float, pe_idx: int) -> tuple[dict[str, float], float]:
    trial_args = SimpleNamespace(
        K=args.K,
        L=args.L,
        M=args.M,
        pe=pe,
        phase=args.phase,
        sic=args.sic,
        match_existing_truncation=True,
    )
    start = time.time()
    metrics = [
        run_trial(trial_args, args.seed + pe_idx * args.trials + trial_idx)
        for trial_idx in range(args.trials)
    ]
    return empirical_summary(metrics), time.time() - start


def build_table(
    args: argparse.Namespace,
    bound_rows: list[BoundRow],
    empirical: dict[float, tuple[dict[str, float], float]],
    practical_bad_masks: list[int],
) -> str:
    lines = [
        "# UACE Bound vs Empirical Trend Overlay",
        "",
        "This table is generated by `research/uace_trend_overlay.py`.",
        "",
        "Regime:",
        "",
        f"- `K = {args.K}`",
        f"- `L = {args.L}`",
        f"- `J = {args.J}`",
        f"- `M = {args.M}`",
        f"- decoder phase: `{args.phase}`",
        f"- `SIC = {args.sic}`",
        f"- empirical trials per `p_e`: `{args.trials}`",
        "",
        "| pe | bound P>=2 era | schedule UE | bound UE geom | bound UE rank | empirical PDP | empirical PHP | empirical P>=2 era | empirical schedule fail | empirical rank fail | seconds |",
        "|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|",
    ]
    for row in bound_rows:
        summary, seconds = empirical.get(row.pe, ({}, 0.0))
        schedule_ue = bad_mask_probability(practical_bad_masks, args.L, row.pe)
        lines.append(
            "| "
            + " | ".join(
                [
                    f"{row.pe:.3f}",
                    format_probability(row.p_two_or_more_erasures),
                    format_probability(schedule_ue),
                    format_probability(row.p_geometric_ue),
                    format_probability(row.p_rank_peeling_ue),
                    format_probability(summary.get("pdp")) if summary else "n/a",
                    format_probability(summary.get("php")) if summary else "n/a",
                    format_probability(summary.get("pge2_erasure_emp")) if summary else "n/a",
                    format_probability(summary.get("schedule_fail_emp")) if summary else "n/a",
                    format_probability(summary.get("rank_fail_emp")) if summary else "n/a",
                    f"{seconds:.2f}" if summary else "n/a",
                ]
            )
            + " |"
        )

    lines.extend(
        [
            "",
            "Reading guide:",
            "",
            "- If empirical PDP follows `bound P>=2 era`, the practical decoder is mostly limited to one-erasure recovery.",
            "- `schedule UE` is the collision-free erasure-only bound induced by the current phase/root schedule.",
            "- If empirical PDP falls toward `bound UE rank`, the decoder is exploiting separated/rank-recoverable multi-erasure patterns.",
            "- `bound phase-II proxy` is intentionally crude: `P[#erasures>=2] + exact collision-run`.  It is useful as a baseline trend, not as a final tight theorem.",
            "- The empirical columns use the current playground decoder behavior; runtime can grow quickly with `K` and `M` because early sections accept many paths before parity checks prune them.",
            "",
        ]
    )
    return "\n".join(lines)


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--K", type=int, default=10)
    parser.add_argument("--L", type=int, default=16)
    parser.add_argument("--J", type=int, default=16)
    parser.add_argument("--M", type=int, default=3)
    parser.add_argument("--phase", type=int, default=2, choices=(1, 2, 3))
    parser.add_argument("--sic", type=int, default=0, choices=(0, 1))
    parser.add_argument("--trials", type=int, default=1)
    parser.add_argument("--seed", type=int, default=0)
    parser.add_argument("--pes", type=float, nargs="+", default=list(DEFAULT_PES))
    parser.add_argument("--skip-empirical", action="store_true")
    parser.add_argument("--output", type=Path, default=None)
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    rank_bad_masks = rank_peeling_bad_masks(args.L, args.M, args.seed)
    practical_bad_masks = schedule_bad_masks(args.L, args.M, args.phase, args.seed)
    bound_rows = [
        compute_row(args.K, args.L, args.J, args.M, pe, rank_bad_masks)
        for pe in args.pes
    ]
    empirical = {}
    if not args.skip_empirical:
        for pe_idx, pe in enumerate(args.pes):
            empirical[pe] = run_empirical_for_pe(args, pe, pe_idx)

    content = build_table(args, bound_rows, empirical, practical_bad_masks)
    if args.output is None:
        print(content)
    else:
        args.output.write_text(content + "\n", encoding="utf-8")
        print(f"wrote {args.output}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
