#!/usr/bin/env python3
"""Audit PHP components for the K=30/K=40 LLC/UACE validation regime."""

from __future__ import annotations

import argparse
import math
from dataclasses import dataclass
from pathlib import Path

from uace_bound_explorer import format_probability
from uace_composite_predictor import composite_rows
from uace_interference_bound import interference_moments


DEFAULT_KS = (30, 40)
DEFAULT_PES = (0.1, 0.2, 0.3)


@dataclass(frozen=True)
class PhpAuditRow:
    k: int
    pe: float
    schedule: float
    pair_preempt: float
    hallucination_php: float
    php_bound: float
    dominant_attempt: str
    dominant_weight: int
    dominant_exponent: int
    dominant_php: float
    pair_needed: int | None
    hallucination_needed: int | None
    composite_needed: int | None


def zero_event_required_trials(rate: float, alpha: float = 0.05) -> int | None:
    if not (0.0 < rate < 1.0):
        return None
    return math.ceil(math.log(alpha) / math.log(1.0 - rate))


def dominant_hallucination_component(args: argparse.Namespace, k: int, pe: float) -> tuple[str, int, int, float]:
    moments = interference_moments(
        k=k,
        length=args.L,
        j=args.J,
        memory=args.M,
        phase=args.phase,
        pe=pe,
        parity_bits_per_section=args.R,
        seed=args.seed,
    )
    best = ("", 0, 0, 0.0)
    for moment in moments:
        for weight, _count, exponent, contribution in moment.weight_contributions:
            php_contribution = contribution / k
            if php_contribution > best[3]:
                best = (moment.name, weight, exponent, php_contribution)
    return best


def audit_rows(args: argparse.Namespace) -> list[PhpAuditRow]:
    comp_rows = composite_rows(args)
    rows: list[PhpAuditRow] = []
    for row in comp_rows:
        dominant_attempt, dominant_weight, dominant_exponent, dominant_php = dominant_hallucination_component(
            args, row.k, row.pe
        )
        rows.append(
            PhpAuditRow(
                k=row.k,
                pe=row.pe,
                schedule=row.schedule,
                pair_preempt=row.pair_preempt,
                hallucination_php=row.hallucination_php,
                php_bound=row.php_bound,
                dominant_attempt=dominant_attempt,
                dominant_weight=dominant_weight,
                dominant_exponent=dominant_exponent,
                dominant_php=dominant_php,
                pair_needed=zero_event_required_trials(row.pair_preempt),
                hallucination_needed=zero_event_required_trials(row.hallucination_php),
                composite_needed=zero_event_required_trials(row.php_bound),
            )
        )
    return rows


def build_report(args: argparse.Namespace) -> str:
    rows = audit_rows(args)
    lines = [
        "# UACE PHP Component Audit",
        "",
        "This report is generated by `research/uace_php_audit.py`.",
        "",
        "The composite phase-III PHP bound is",
        "",
        "$$",
        "\\widehat{\\mathrm{PHP}}_{\\mathrm{III}}",
        "\\le",
        "P_{\\mathrm{pair\\text{-}preempt}}+P_{\\mathrm{hallucination}}.",
        "$$",
        "",
        "`P_pair-preempt` is the exact two-color affine-rank finite-instance union term.  `P_hallucination` is the rank-corrected first-moment Markov term over parity-consistent false survivors.",
        "",
        "## Component Table",
        "",
        "| K | pe | pair-preempt | pure hallucination | composite PHP bound | pair / hallucination | dominant hallucination component | dominant PHP contribution | zero-event checks for composite scale |",
        "|---:|---:|---:|---:|---:|---:|---|---:|---:|",
    ]
    for row in rows:
        ratio = row.pair_preempt / row.hallucination_php if row.hallucination_php > 0 else float("inf")
        component_attempt = row.dominant_attempt
        if (
            args.phase == 3
            and row.dominant_attempt == "phase-III root 0"
            and row.dominant_weight == 2
        ):
            component_attempt = "phase-III root 0/root 6 (tie)"
        component = f"{component_attempt}, w={row.dominant_weight}, e={row.dominant_exponent}"
        lines.append(
            "| "
            + " | ".join(
                [
                    str(row.k),
                    f"{row.pe:.3f}",
                    format_probability(row.pair_preempt),
                    format_probability(row.hallucination_php),
                    format_probability(row.php_bound),
                    format_probability(ratio),
                    component,
                    format_probability(row.dominant_php),
                    str(row.composite_needed) if row.composite_needed is not None else "n/a",
                ]
            )
            + " |"
        )

    lines.extend(
        [
            "",
            "## Zero-Event Sample Requirements",
            "",
            "The entries below are user-equivalent zero-event checks needed for a one-sided 95% empirical upper bound to fall below the listed analytic scale.",
            "",
            "| K | pe | pair scale checks | pure hallucination scale checks | composite PHP scale checks |",
            "|---:|---:|---:|---:|---:|",
        ]
    )
    for row in rows:
        lines.append(
            "| "
            + " | ".join(
                [
                    str(row.k),
                    f"{row.pe:.3f}",
                    str(row.pair_needed) if row.pair_needed is not None else "n/a",
                    str(row.hallucination_needed) if row.hallucination_needed is not None else "n/a",
                    str(row.composite_needed) if row.composite_needed is not None else "n/a",
                ]
            )
            + " |"
        )

    lines.extend(
        [
            "",
            "Readout:",
            "",
            "- In the tested K=30/K=40 regime, the composite PHP bound is dominated by the exact pair-preemption term, not by pure hallucination.",
            "- The pure hallucination first moment is dominated by phase-III root 0/root 6, weight-2 accepted shapes with rank exponent 96.",
            "- Ordinary Monte Carlo cannot resolve the pure hallucination scale; even the composite PHP scale needs tens of thousands of user-equivalent zero-event checks.",
            "- Therefore PHP validation should be presented as analytic finite-instance control plus implementation sanity probes, not as direct empirical measurement of a visible event rate.",
            "",
        ]
    )
    return "\n".join(lines)


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--L", type=int, default=16)
    parser.add_argument("--M", type=int, default=3)
    parser.add_argument("--J", type=int, default=16)
    parser.add_argument("--R", type=int, default=8)
    parser.add_argument("--phase", type=int, default=3)
    parser.add_argument("--seed", type=int, default=0)
    parser.add_argument("--Ks", type=int, nargs="+", default=list(DEFAULT_KS))
    parser.add_argument("--pes", type=float, nargs="+", default=list(DEFAULT_PES))
    parser.add_argument("--pair-file", type=Path, default=Path("research/uace_pair_preemption_exact.md"))
    parser.add_argument("--output", type=Path, default=Path("research/uace_php_audit.md"))
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    content = build_report(args)
    if args.output:
        args.output.write_text(content + "\n", encoding="utf-8")
        print(f"wrote {args.output}")
    else:
        print(content)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
