#!/usr/bin/env python3
"""Generate a compact summary of current LLC UACE bounds."""

from __future__ import annotations

import argparse
from pathlib import Path

from uace_bound_explorer import (
    bad_mask_probability,
    erasure_count_tail,
    format_probability,
    rank_peeling_bad_masks,
    tagged_collision_probability,
    circular_run_probability,
)
from uace_schedule_bound import schedule_bad_masks


def build_summary(args: argparse.Namespace) -> str:
    rank_bad = rank_peeling_bad_masks(args.L, args.M, args.seed)
    phase2_bad = schedule_bad_masks(args.L, args.M, 2, args.seed)
    phase3_bad = schedule_bad_masks(args.L, args.M, 3, args.seed)

    lines = [
        "# LLC UACE Bound Summary",
        "",
        "This summary is generated by `research/uace_bound_summary.py`.",
        "",
        f"- `L = {args.L}`",
        f"- `M = {args.M}`",
        f"- `J = {args.J}`",
        f"- `K = {args.K}` for collision-scale columns",
        f"- matrix seed: `{args.seed}`",
        "",
        "| pe | phase-II schedule | phase-III schedule | ideal rank-peeling | P[#era>=2] | 3-collision run |",
        "|---:|---:|---:|---:|---:|---:|",
    ]
    for pe in args.pes:
        rho = tagged_collision_probability(args.K, args.J, pe)
        collision_run = circular_run_probability(args.L, args.M, rho)
        lines.append(
            "| "
            + " | ".join(
                [
                    f"{pe:.3f}",
                    format_probability(bad_mask_probability(phase2_bad, args.L, pe)),
                    format_probability(bad_mask_probability(phase3_bad, args.L, pe)),
                    format_probability(bad_mask_probability(rank_bad, args.L, pe)),
                    format_probability(erasure_count_tail(args.L, pe, 2)),
                    format_probability(collision_run),
                ]
            )
            + " |"
        )

    lines.extend(
        [
            "",
            "Interpretation:",
            "",
            "- `phase-II schedule` is exactly the one-erasure decoding floor for the current phase-II schedule.",
            "- `phase-III schedule` is the current decoder's erasure-only prediction after the phase-II-e attempts.",
            "- `ideal rank-peeling` is the LLC erasure-recovery potential if root/order restrictions are removed.",
            "- `3-collision run` is tiny in this regime, so PDP trends should be erasure/schedule dominated.",
            "",
            "Empirical anchors already generated:",
            "",
            "- `research/uace_trend_overlay_K6.md`: phase-II pilots track empirical schedule fail.",
            "- `research/uace_trend_overlay_K6_phase3_pe010_trials3.md`: phase-III PDP equals empirical schedule fail in the sampled masks.",
            "- `research/uace_empirical_probe_K30_pe010.md`: phase-II PDP equals sampled `P[#era>=2]`.",
            "",
        ]
    )
    return "\n".join(lines)


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--L", type=int, default=16)
    parser.add_argument("--M", type=int, default=3)
    parser.add_argument("--J", type=int, default=16)
    parser.add_argument("--K", type=int, default=100)
    parser.add_argument("--seed", type=int, default=0)
    parser.add_argument("--pes", type=float, nargs="+", default=[0, 0.025, 0.05, 0.075, 0.1, 0.15, 0.2])
    parser.add_argument("--output", type=Path, default=None)
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    content = build_summary(args)
    if args.output is None:
        print(content)
    else:
        args.output.write_text(content + "\n", encoding="utf-8")
        print(f"wrote {args.output}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
