#!/usr/bin/env python3
"""Inventory accepted LLC erasure shapes by attempt and gap pattern."""

from __future__ import annotations

import argparse
from collections import Counter
from pathlib import Path

from uace_bound_explorer import load_repo_code_matrices
from uace_schedule_bound import attempt_succeeds, mask_to_sections, schedule_attempts


def circular_gap_pair(a: int, b: int, length: int) -> tuple[int, int]:
    gap = (b - a) % length
    other = length - gap
    return tuple(sorted((gap, other)))


def build_report(args: argparse.Namespace) -> str:
    message_lens, _parity_lens, gijs = load_repo_code_matrices(args.L, args.M, args.seed)
    lines = [
        "# Accepted Erasure-Shape Inventory",
        "",
        "This report is generated by `research/uace_accepted_shape_inventory.py`.",
        "",
        f"- `L = {args.L}`",
        f"- `M = {args.M}`",
        f"- phase: `{args.phase}`",
        "",
        "| attempt | weight | count | gap/profile summary |",
        "|---|---:|---:|---|",
    ]
    detail_lines = ["", "## Two-Erasure Details", ""]
    for name, root, d, erasure_slot in schedule_attempts(args.L, args.phase):
        by_weight: Counter[int] = Counter()
        gap_counter: Counter[tuple[int, int]] = Counter()
        examples: dict[tuple[int, int], list[tuple[int, ...]]] = {}
        for mask in range(1 << args.L):
            if not attempt_succeeds(
                mask,
                length=args.L,
                memory=args.M,
                root=root,
                d=d,
                erasure_slot=erasure_slot,
                message_lens=message_lens,
                gijs=gijs,
            ):
                continue
            sections = mask_to_sections(mask, args.L)
            by_weight[len(sections)] += 1
            if len(sections) == 2:
                gap = circular_gap_pair(sections[0], sections[1], args.L)
                gap_counter[gap] += 1
                examples.setdefault(gap, []).append(sections)
        for weight, count in sorted(by_weight.items()):
            summary = ""
            if weight == 2 and gap_counter:
                summary = ", ".join(f"{gap}:{count}" for gap, count in sorted(gap_counter.items()))
            lines.append(f"| {name} | {weight} | {count} | {summary} |")
        if gap_counter:
            detail_lines.extend([f"### {name}", "", "| circular gaps | count | examples |", "|---|---:|---|"])
            for gap, count in sorted(gap_counter.items()):
                sample = "; ".join(str(item) for item in examples[gap][: args.examples])
                detail_lines.append(f"| {gap} | {count} | {sample} |")
            detail_lines.append("")
    return "\n".join(lines + detail_lines)


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--L", type=int, default=16)
    parser.add_argument("--M", type=int, default=3)
    parser.add_argument("--phase", type=int, default=3, choices=(1, 2, 3))
    parser.add_argument("--seed", type=int, default=0)
    parser.add_argument("--examples", type=int, default=4)
    parser.add_argument("--output", type=Path, default=Path("research/uace_accepted_shape_inventory.md"))
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    content = build_report(args)
    if args.output:
        args.output.write_text(content + "\n", encoding="utf-8")
        print(f"wrote {args.output}")
    else:
        print(content)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
