#!/usr/bin/env python3
"""Exact parity-rank exponent profiles for LLC/UACE erasure masks."""

from __future__ import annotations

import argparse
from collections import Counter, defaultdict
from pathlib import Path

import numpy as np

from uace_bound_explorer import (
    cantor_pairing,
    gf2_rank,
    load_repo_code_matrices,
    who_decides_p_sec,
)
from uace_schedule_bound import attempt_succeeds, mask_to_sections, schedule_attempts


def bit_is_erased(mask: int, section: int) -> bool:
    return ((mask >> section) & 1) == 1


def parity_rank_exponent(mask: int, length: int, memory: int, message_lens: np.ndarray, parity_lens: np.ndarray, gijs: dict) -> tuple[int, int, int]:
    """Return (exponent, rank_full, rank_unknown) for one erased-section mask.

    Observed parity equations have the form

        A x_erased + B z_known = 0.

    For uniform known section symbols, the probability that an erased-info
    assignment exists is 2^{-(rank([A B]) - rank(A))}.
    """
    erased = {idx for idx in range(length) if bit_is_erased(mask, idx)}
    unknown_offsets = {}
    unknown_cols = 0
    for section in sorted(erased):
        unknown_offsets[section] = unknown_cols
        unknown_cols += int(message_lens[section])

    known_info_offsets = {}
    known_cols = 0
    for section in range(length):
        if section not in erased:
            known_info_offsets[section] = known_cols
            known_cols += int(message_lens[section])

    known_parity_offsets = {}
    for section in range(length):
        if section not in erased:
            known_parity_offsets[section] = known_cols
            known_cols += int(parity_lens[section])

    rows = int(sum(parity_lens[section] for section in range(length) if section not in erased))
    mat_unknown = np.zeros((rows, unknown_cols), dtype=np.uint8)
    mat_known = np.zeros((rows, known_cols), dtype=np.uint8)

    row_offset = 0
    for section in range(length):
        if section in erased:
            continue
        width = int(parity_lens[section])
        parity_start = known_parity_offsets[section]
        mat_known[row_offset : row_offset + width, parity_start : parity_start + width] = np.eye(width, dtype=np.uint8)

        for decider in who_decides_p_sec(length, section, memory):
            block = np.array(gijs[cantor_pairing(decider, section)], dtype=np.uint8).T
            if decider in erased:
                col = unknown_offsets[decider]
                mat_unknown[row_offset : row_offset + width, col : col + int(message_lens[decider])] ^= block
            else:
                col = known_info_offsets[decider]
                mat_known[row_offset : row_offset + width, col : col + int(message_lens[decider])] ^= block
        row_offset += width

    if unknown_cols == 0:
        rank_unknown = 0
        full = mat_known
    else:
        rank_unknown = gf2_rank(mat_unknown)
        full = np.concatenate([mat_unknown, mat_known], axis=1)
    rank_full = gf2_rank(full)
    return rank_full - rank_unknown, rank_full, rank_unknown


def circular_gap_pair(a: int, b: int, length: int) -> tuple[int, int]:
    gap = (b - a) % length
    return tuple(sorted((gap, length - gap)))


def build_report(args: argparse.Namespace) -> str:
    message_lens, parity_lens, gijs = load_repo_code_matrices(args.L, args.M, args.seed)
    lines = [
        "# LLC/UACE Parity-Rank Exponent Profile",
        "",
        "This report is generated by `research/uace_parity_rank_profile.py`.",
        "",
        f"- `L = {args.L}`",
        f"- `M = {args.M}`",
        f"- phase: `{args.phase}`",
        "",
        "| attempt | weight | masks | exponent profile | naive exponent | min rank(A) | max rank(A) |",
        "|---|---:|---:|---|---:|---:|---:|",
    ]

    detail_lines = ["", "## Dominant Two-Erasure Details", ""]
    for name, root, d, erasure_slot in schedule_attempts(args.L, args.phase):
        by_weight: dict[int, Counter[int]] = defaultdict(Counter)
        unknown_rank_by_weight: dict[int, list[int]] = defaultdict(list)
        gap_rank: Counter[tuple[tuple[int, int], int]] = Counter()
        for mask in range(1 << args.L):
            if not attempt_succeeds(
                mask,
                length=args.L,
                memory=args.M,
                root=root,
                d=d,
                erasure_slot=erasure_slot,
                message_lens=message_lens,
                gijs=gijs,
            ):
                continue
            sections = mask_to_sections(mask, args.L)
            exponent, _rank_full, rank_unknown = parity_rank_exponent(
                mask,
                args.L,
                args.M,
                message_lens,
                parity_lens,
                gijs,
            )
            weight = len(sections)
            by_weight[weight][exponent] += 1
            unknown_rank_by_weight[weight].append(rank_unknown)
            if weight == 2:
                gap_rank[(circular_gap_pair(sections[0], sections[1], args.L), exponent)] += 1

        for weight, counter in sorted(by_weight.items()):
            profile = ", ".join(f"{exp}:{count}" for exp, count in sorted(counter.items()))
            ranks = unknown_rank_by_weight[weight]
            naive = int((args.L - weight) * parity_lens[0])
            lines.append(
                f"| {name} | {weight} | {sum(counter.values())} | {profile} | {naive} | {min(ranks)} | {max(ranks)} |"
            )
        if gap_rank:
            detail_lines.extend([f"### {name}", "", "| circular gaps | exponent | count |", "|---|---:|---:|"])
            for (gap, exponent), count in sorted(gap_rank.items()):
                detail_lines.append(f"| {gap} | {exponent} | {count} |")
            detail_lines.append("")

    lines.extend(
        [
            "",
            "Readout:",
            "",
            "- `exponent` is `rank([A B]) - rank(A)` in the existential erased-info system.",
            "- Equality with the naive exponent `r(L-w)` means the erased-info degrees of freedom remove exactly `wr` parity constraints and no additional rank loss occurs.",
            "",
        ]
    )
    return "\n".join(lines + detail_lines)


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--L", type=int, default=16)
    parser.add_argument("--M", type=int, default=3)
    parser.add_argument("--phase", type=int, default=3, choices=(1, 2, 3))
    parser.add_argument("--seed", type=int, default=0)
    parser.add_argument("--output", type=Path, default=Path("research/uace_parity_rank_profile.md"))
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    content = build_report(args)
    if args.output:
        args.output.write_text(content + "\n", encoding="utf-8")
        print(f"wrote {args.output}")
    else:
        print(content)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
